version: '2'

services:     
  ttnode:
    # 测试用
    # image: ericwang2006/ttnode:test
    image: ericwang2006/ttnode
    # 内存限制
    mem_limit: 1024m
    container_name: ttnode
    hostname: ttnode1
    privileged: true
    restart: always
    mac_address: C2:F2:9C:C5:B2:94
    dns: 114.114.114.114
    networks: 
      macvlan:
        ipv4_address: 192.168.2.2
    volumes:
      # issues#16 提到的 配置文件
      - ./config:/config
      - /mnt/data/ttnode:/mnts

networks:
  macvlan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.2.1
